import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "360px",
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
    },
    extend: {

      backgroundImage: {
        "gradient-mobile-nav": "linear-gradient(56deg, #1645FF 0.2%, #0B1B55 39.43%, #05070D 62.49%)",
        "grad-3": "linear-gradient(102deg, rgba(164, 183, 255, 0.20) 0%, rgba(142, 163, 240, 0.20) 23.47%, rgba(20, 49, 153, 0) 109.89%)",
        "cutout-curve": "radial-gradient(circle at top right, transparent 20px, var(--color-surface) 0)",
      },
      
      fontFamily: {
        sans: ["var(--font-mulish)", "sans-serif"],
        mulish: ["var(--font-mulish)", "sans-serif"],
      },
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-hover)",
          muted: "var(--color-primary-muted)",
          pale: "var(--color-primary-pale)",
          border: "var(--color-primary-border)",
        },
        brand: {
          primary: "var(--color-primary)",
          border: "var(--color-primary-border)",
          light: "var(--color-primary-muted)",
          pale: "var(--color-primary-pale)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          dark: "var(--color-surface-dark)",
          darker: "var(--color-surface-darker)",
        },
        ink: {
          DEFAULT: "var(--color-ink)",
          muted: "var(--color-ink-muted)",
          subtle: "var(--color-ink-subtle)",
          watermark: "var(--color-ink-watermark)",
        },
        border: {
          subtle: "var(--color-border-subtle)",
          card: "var(--color-border-card)",
        },
        success: "var(--color-success)",
        error: "var(--color-error)",
        warning: "var(--color-warning)",
        info: "var(--color-info)",
        footer: {
          icon: "var(--color-footer-icon)",
        },
      },
      maxWidth: {
        container: "80rem",
        "container-xl": "1400px",
        "container-2xl": "1600px",
        "container-wide": "1800px",
      },
      width: {
        "cta-button": "296px",
      },
      height: {
        panel: "400px",
      },
      aspectRatio: {
        "media-wrap": "600 / 484",
        "media-main": "454 / 420",
        "media-sec": "256 / 240",
      },
      borderRadius: {
        btn: "var(--radius-btn)",
        card: "var(--radius-card)",
        "card-sm": "var(--radius-card-sm)",
        hero:"var(--radius-card-radius)",
        "card-md": "20px",
        "card-lg": "var(--radius-card-lg)",
        "page-hero": "18px",
        "split-image": "23.56px",
        "card-grid": "15px",
        "4xl": "32px",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-active": "var(--shadow-card-active)",
        focus: "var(--shadow-focus)",
        "glow-primary": "var(--shadow-glow-primary)",
        "help-card": "var(--shadow-help-card)",
      },
      spacing: {
        "space-2": "2px",
        "space-4": "4px",
        "space-6": "6px",
        "space-8": "8px",
        "space-10": "10px",
        "space-12": "12px",
        "space-14": "14px",
        "space-16": "16px",
        "space-20": "20px",
        "space-24": "24px",
        "space-32": "32px",
        "space-36": "36px",
        "space-40": "40px",
        "space-48": "48px",
        "space-50": "50px",
        "space-56": "56px",
        "space-60": "60px",
        "space-64": "64px",
        "space-80": "80px",
        "space-100": "100px",
        "cm-wrap-mob": "289px",
        "cm-main-w-mob": "271px",
        "cm-main-h-mob": "251px",
        "cm-sec-w-mob": "153px",
        "cm-sec-h-mob": "143px",
        "cm-sec-left": "11px",
        "cm-wrap-dt": "600px",
        "cm-wrap-h-dt": "484px",
        "cm-main-w-dt": "454px",
        "cm-main-h-dt": "420px",
        "cm-sec-w-dt": "256px",
        "cm-sec-h-dt": "240px",
      },
      fontSize: {
        "hero-header-eb": ["56px", { fontWeight: "800", lineHeight: "70px" }],
        "section-title": ["48px", { fontWeight: "800", lineHeight: "1.2" }],
        "section-title-mobile": ["24px", { fontWeight: "800", lineHeight: "1.2" }],
        "section-subtitle": ["20px", { fontWeight: "400", lineHeight: "1.5" }],
        "section-subtitle-mobile": ["14px", { fontWeight: "400", lineHeight: "1.5" }],
        "card-title": ["32px", { fontWeight: "700", lineHeight: "1.2" }],
        "card-title-desktop": ["24px", { fontWeight: "600", lineHeight: "1.2" }],
        "card-title-mobile": ["20px", { fontWeight: "800", lineHeight: "1.2" }],
        "card-desc": ["16px", { fontWeight: "400", lineHeight: "1.5" }],
        "card-desc-mobile": ["12px", { fontWeight: "400", lineHeight: "1.5" }],
        "eyebrow-mobile": ["10px", { fontWeight: "800", lineHeight: "1.5" }],
        "eyebrow-desktop": ["16px", { fontWeight: "600", lineHeight: "1", letterSpacing: "1px" }],
        "link-mobile": ["14px", { fontWeight: "600", lineHeight: "1.5" }],
        "link-desktop": ["16px", { fontWeight: "600", lineHeight: "1.5" }],
        "cta-title-mobile": ["24px", { fontWeight: "700", lineHeight: "1.2" }],
        "cta-title-desktop": ["32px", { fontWeight: "700", lineHeight: "1.2" }],
        "cta-expert-desktop": ["16px", { fontWeight: "400", lineHeight: "1.25" }],
        "footer-heading-desktop": ["12px", { fontWeight: "700", lineHeight: "1.5" }],
        "footer-media-heading-desktop": ["24px", { fontWeight: "400", lineHeight: "1.3" }],
        "footer-media-cta-desktop": ["14px", { fontWeight: "600", lineHeight: "1.5" }],
        "help-card-title": ["24px", { fontWeight: "600", lineHeight: "32px" }],
        "help-card-title-mobile": ["20px", { fontWeight: "600", lineHeight: "28px" }],
        "help-card-title-desktop": ["20px", { fontWeight: "700", lineHeight: "1.2" }], 
        "help-card-prefix": ["12px", { fontWeight: "600", lineHeight: "18px", letterSpacing: "1px" }],
        "help-card-prefix-mobile": ["12px", { fontWeight: "600", lineHeight: "18px", letterSpacing: "1px" }],
        "help-card-prefix-blue-mobile": ["12px", { fontWeight: "400", lineHeight: "18px", letterSpacing: "1px" }],
        "help-card-desc-mobile": ["14px", { fontWeight: "400", lineHeight: "1.5" }],
        "numbers": ["80px", { fontWeight: "700", lineHeight: "1.5" }],
        "numbers-mobile": ["48px", { fontWeight: "700", lineHeight: "1.5" }],
        "section-title-head-mobile": ["14px", { fontWeight: "700", lineHeight: "1.571" }],
        "section-title-head": ["24px", { fontWeight: "600", lineHeight: "1.333" }],
        "section-title-h": ["18px", { fontWeight: "400", lineHeight: "1.5" }],
        "link-card-mobile": ["10px", { fontWeight: "600", lineHeight: "1.5" }],
        "card-detail-mobile": ["10px", { fontWeight: "400", lineHeight: "1.5" }],
        "stat-desc-mobile": ["10px", { fontWeight: "400", lineHeight: "1.4" }],
        "cta-text2-sb-mobile": ["10px", { fontWeight: "600", lineHeight: "1.4" }],
        "heading2-sb-mobile": ["16px", { fontWeight: "600", lineHeight: "1.5" }],
        "about-eyebrow-desktop": ["12px", { fontWeight: "600", lineHeight: "1.5" }],
        "page-hero-title": ["56px", { fontWeight: "800", lineHeight: "70px", letterSpacing: "0px" }],
        "page-hero-subtitle": ["20px", { fontWeight: "400", lineHeight: "28px", letterSpacing: "0px" }],
        "page-hero-eyebrow": ["16px", { fontWeight: "600", lineHeight: "16px", letterSpacing: "1px" }],
        "split-section-title": ["48px", { fontWeight: "800", lineHeight: "68px", letterSpacing: "0px" }],
      },
    },
  },
  plugins: [],
};

export default config;