import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import TopBar from "../components/layout/TopBar/TopBar";
import Navbar from "../components/layout/Navbar/Navbar";
import Footer from "../components/layout/Footer/Footer";
import { ContactModalProvider } from "../components/features/contact/ContactModal/ContactModalProvider";

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Cordinit | Secure Digital Transformation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ContactModalProvider>
          <TopBar />
          <Navbar />
          {children}
          <Footer />
        </ContactModalProvider>
      </body>
    </html>
  );
}
