import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/layout/TopBar/TopBar";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import { ContactModalProvider } from "@/components/features/contact/ContactModal/ContactModalProvider";
import { NewsletterModalProvider } from "@/components/features/newsletter/NewsletterModal/NewsletterModalProvider";
import CtaSection from "@/components/features/home/CtaSection/CtaSection";

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Cordinit | Secure Digital Transformation",
  description: "Generated by create next app",
  icons: {
    icon: '/fev.svg',
  }
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} font-sans h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <ContactModalProvider>
          <NewsletterModalProvider>
            <TopBar />
            <Navbar />
            {children}
            <CtaSection />
            <Footer />
          </NewsletterModalProvider>
        </ContactModalProvider>
      </body>
    </html>
  );
}
