import { TestimonialItem } from './types';

export const defaultItems: TestimonialItem[] = [
  {
    id: 1,
    name: "Mohommed Rashid Khan",
    role: "Director & Chief Executive Officer",
    company: "Cordinit Group",
    quote: '"Security isn\'t just about protection. It\'s about creating the confidence to move faster."',
    image: "/testimonial/image.png",
  },
  {
    id: 2,
    name: "Christina Adams",
    role: "Global Chief Communications Officer",
    company: "Cordinit Media",
    quote: '"The architectural clarity Cordinit brings has transformed how our board understands risk posture."',
    image: "/testimonial/image copy.png",
  },
  {
    id: 3,
    name: "TBA",
    role: "Global Brand President",
    company: "Cordinit Media",
    quote: '"Scalability without compromise. It\'s rare to find a platform that delivers both operational rigor and agility."',
    image: "/testimonial/image copy 2.png",
  },
  {
    id: 4,
    name: "TBA",
    role: "Chief Financial Officer",
    company: "Cordint Group",
    quote: '"We deployed their framework in weeks, not months. The precision is unmatched."',
    image: "/testimonial/image copy 3.png",
  },
  {
    id: 5,
    name: "TBA",
    role: "Co-President and Co-Chief Operating Officer",
    company: "Cordinit Group",
    quote: '"Security isn\'t just about protection. It\'s about creating the confidence to move faster."',
    image: "/testimonial/image copy 4.png",
  },
  {
    id: 6,
    name: "TBA",
    role: "Executive Vice President",
    company: "Cordinit Group",
    quote: '"The architectural clarity Cordinit brings has transformed how our board understands risk posture."',
    image: "/testimonial/image copy 5.png",
  },
  {
    id: 7,
    name: "TBA",
    role: "Chief Talent Officer",
    company: "Cordinit Technologies & Media",
    quote: '"Scalability without compromise. It\'s rare to find a platform that delivers both operational rigor and agility."',
    image: "/testimonial/image.png",
  },
  {
    id: 8,
    name: "TBA",
    role: "Member of the Governance and Finance Committees",
    company: "Cordinit Group",
    quote: '"We deployed their framework in weeks, not months. The precision is unmatched."',
    image: "/testimonial/image copy.png",
  },
  {
    id: 9,
    name: "TBA",
    role: "Member of the Audit and Finance Committees",
    company: "Cordinit Group",
    quote: '"Security isn\'t just about protection. It\'s about creating the confidence to move faster."',
    image: "/testimonial/image copy 2.png",
  },
  {
    id: 10,
    name: "TBA",
    role: "Member of the Compensation Committee",
    company: "Cordinit Group",
    quote: '"The architectural clarity Cordinit brings has transformed how our board understands risk posture."',
    image: "/testimonial/image copy 3.png",
  },
  {
    id: 11,
    name: "TBA",
    role: "Chief Client and Business Officer",
    company: "Cordinit Media",
    quote: '"Scalability without compromise. It\'s rare to find a platform that delivers both operational rigor and agility."',
    image: "/testimonial/image copy 4.png",
  }
];
